package com.matthias.synthesiavideotomidi.gui;

import com.matthias.synthesiavideotomidi.bl.ConverterBL;
import com.matthias.synthesiavideotomidi.bl.DefaultData;
import com.matthias.synthesiavideotomidi.bl.NoteListener;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Matthias
 */
public class ConverterGUI extends javax.swing.JFrame {

    private final JFileChooser fileChooser = new JFileChooser();
    private String waiting = "c1";
    private double scale = 1;
    private int fps = 5;
    
    ConverterBL bl = new ConverterBL();

    public ConverterGUI() {
        initComponents();
        setSize(new Dimension(1500, 800));
        reset();
    }
    
    public void reset() {
        bl.reset();
        waiting="c1";
        lbAction.setText("Action: set c" + (int) spC1.getValue());
        scale = sliderScale.getValue() / 100.0;
        fps = sliderFPS.getValue();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        try {
            Graphics2D g2 = (Graphics2D) pnCanvas.getGraphics();
            g2.setColor(Color.gray);
            BufferedImage bufferedImage = bl.getCurrentFrame();
            if (bufferedImage == null) {
                return;
            }
            g2.drawImage(bufferedImage, 0, 0, (int) (bufferedImage.getWidth() * scale), (int) (bufferedImage.getHeight() * scale), this);

            if (bl.getState() != ConverterBL.RUNNING) {
                for (NoteListener nl : bl.getNoteListeners()) {
                    g2.setColor(Color.orange);
                    g2.fillRect((int) (nl.getPosX() * scale - 2), (int) (nl.getPosY() * scale - 2), 4, 4);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setSpinnerTexts(DefaultData data) {
        spC1.setValue(data.getC1());
        spC2.setValue(data.getC2());
        spBPM.setValue(data.getBpm());
        spPPQ.setValue(data.getPpq());
        spStartFrame.setValue(data.getStartFrame());
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnCanvas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btSetC1 = new javax.swing.JButton();
        btSetC2 = new javax.swing.JButton();
        btStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spBPM = new javax.swing.JSpinner();
        spC1 = new javax.swing.JSpinner();
        spC2 = new javax.swing.JSpinner();
        btChooseFile = new javax.swing.JButton();
        btFix = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spStartFrame = new javax.swing.JSpinner();
        lbAction = new javax.swing.JLabel();
        spOffC1 = new javax.swing.JSpinner();
        spOffC2 = new javax.swing.JSpinner();
        sliderFPS = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        sliderScale = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spPPQ = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbSingleVoice = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCanvasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnCanvasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnCanvasMouseExited(evt);
            }
        });
        pnCanvas.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(pnCanvas, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 132));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btSetC1.setText("setC");
        btSetC1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btSetC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetC1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(btSetC1, gridBagConstraints);

        btSetC2.setText("setC");
        btSetC2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btSetC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetC2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(btSetC2, gridBagConstraints);

        btStart.setText("start");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(btStart, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("bpm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        spBPM.setModel(new javax.swing.SpinnerNumberModel(150, 1, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        jPanel1.add(spBPM, gridBagConstraints);

        spC1.setModel(new javax.swing.SpinnerNumberModel(2, 0, 8, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(spC1, gridBagConstraints);

        spC2.setModel(new javax.swing.SpinnerNumberModel(8, 0, 8, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(spC2, gridBagConstraints);

        btChooseFile.setText("Choose Video");
        btChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btChooseFile, gridBagConstraints);

        btFix.setText("fix");
        btFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btFix, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("start frame");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        spStartFrame.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));
        spStartFrame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spStartFrameStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(spStartFrame, gridBagConstraints);

        lbAction.setText("Action: nothing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lbAction, gridBagConstraints);

        spOffC1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(spOffC1, gridBagConstraints);

        spOffC2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(spOffC2, gridBagConstraints);

        sliderFPS.setMaximum(20);
        sliderFPS.setMinimum(1);
        sliderFPS.setValue(15);
        sliderFPS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFPSStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(sliderFPS, gridBagConstraints);

        jLabel3.setText("FPS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel1.add(jLabel3, gridBagConstraints);

        sliderScale.setMaximum(150);
        sliderScale.setMinimum(20);
        sliderScale.setValue(100);
        sliderScale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderScaleStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(sliderScale, gridBagConstraints);

        jLabel4.setText("Scale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("ppq (rec: 2,4,12)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel5, gridBagConstraints);

        spPPQ.setModel(new javax.swing.SpinnerNumberModel(4, 1, 120, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(spPPQ, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel6, gridBagConstraints);

        cbSingleVoice.setText("Single Voice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cbSingleVoice, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSetC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetC1ActionPerformed
        waiting = "c1";
        lbAction.setText("Action: set c" + (int) spC1.getValue());
    }//GEN-LAST:event_btSetC1ActionPerformed

    private void pnCanvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCanvasMouseClicked
        if (waiting.equals("c1")) {
            bl.setC1(evt.getX() / scale, evt.getY() / scale, (int) spC1.getValue(),
                    (int) spOffC1.getValue(), (int) spOffC2.getValue());
            waiting = "c2";
            lbAction.setText("Action: set c" + (int) spC2.getValue());
        } else if (waiting.equals("c2")) {
            bl.setC2(evt.getX() / scale, evt.getY() / scale, (int) spC2.getValue(),
                    (int) spOffC1.getValue(), (int) spOffC2.getValue());
            waiting = "fix";
            lbAction.setText("Action: fix");
        } else if (waiting.equals("fix")) {
            bl.fix(evt.getX(), evt.getY());
        }
        repaint();
    }//GEN-LAST:event_pnCanvasMouseClicked

    private void btSetC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetC2ActionPerformed
        waiting = "c2";
        lbAction.setText("Action: set c" + (int) spC2.getValue());
    }//GEN-LAST:event_btSetC2ActionPerformed

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        if (bl.getState() == ConverterBL.WAITING_TO_START) {
            bl.reset();
            try {
                bl.convert(cbSingleVoice.isSelected());
                btStart.setText("Stop");
                Thread t = new Thread(() -> {
                    while (bl.getState() == ConverterBL.RUNNING) {
                        repaint();
                        try {
                            Thread.sleep(1000/fps);
                        } catch (InterruptedException ex) {}
                    }
                    btStart.setText("save");
                });
                t.start();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Converting has failed");
            }
        } else if (bl.getState() == ConverterBL.RUNNING) {
            bl.setState(ConverterBL.WAITING_FOR_SETTINGS);
            btStart.setText("Save");
        } else if (bl.getState() == ConverterBL.WAITING_FOR_SETTINGS) {
            boolean result = bl.setBpmPpq((int) spBPM.getValue(), (int) spPPQ.getValue());
            if(!result) {
                JOptionPane.showMessageDialog(this, "bpm or ppq invalid");
            }
        }

    }//GEN-LAST:event_btStartActionPerformed

    private void btChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseFileActionPerformed
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Matthias\\Documents\\Klavier"));
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            bl.reset();
            setSpinnerTexts(bl.setFile(file));
            repaint();
        }
    }//GEN-LAST:event_btChooseFileActionPerformed

    private void btFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFixActionPerformed
        waiting = "fix";
    }//GEN-LAST:event_btFixActionPerformed

    private void pnCanvasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCanvasMouseEntered
        bl.paused = false;
    }//GEN-LAST:event_pnCanvasMouseEntered

    private void pnCanvasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCanvasMouseExited
        bl.paused = true;
    }//GEN-LAST:event_pnCanvasMouseExited

    private void spStartFrameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spStartFrameStateChanged
        bl.setStartFrame((int) spStartFrame.getValue());
        repaint();
    }//GEN-LAST:event_spStartFrameStateChanged

    private void sliderFPSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFPSStateChanged
        fps = sliderFPS.getValue();
    }//GEN-LAST:event_sliderFPSStateChanged

    private void sliderScaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderScaleStateChanged
        scale = sliderScale.getValue() / 100.0;
        repaint();
    }//GEN-LAST:event_sliderScaleStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bl.saveDefaults();
    }//GEN-LAST:event_formWindowClosing

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConverterGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChooseFile;
    private javax.swing.JButton btFix;
    private javax.swing.JButton btSetC1;
    private javax.swing.JButton btSetC2;
    private javax.swing.JButton btStart;
    private javax.swing.JCheckBox cbSingleVoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAction;
    private javax.swing.JPanel pnCanvas;
    private javax.swing.JSlider sliderFPS;
    private javax.swing.JSlider sliderScale;
    private javax.swing.JSpinner spBPM;
    private javax.swing.JSpinner spC1;
    private javax.swing.JSpinner spC2;
    private javax.swing.JSpinner spOffC1;
    private javax.swing.JSpinner spOffC2;
    private javax.swing.JSpinner spPPQ;
    private javax.swing.JSpinner spStartFrame;
    // End of variables declaration//GEN-END:variables
}
